# ==============================================================================
# 03_trust_models.R — Panel models for trust outcomes + AMEs + γ−β contrasts
# ------------------------------------------------------------------------------
# Inputs:
#   data/dt_states.rds  (generated by 02_latent_markov.R)
# Outputs (output/):
#   - trust_ame_table.csv
#   - trust_models_glance.txt
#   - wald_gamma_minus_beta.txt
# ==============================================================================

source(here::here("code", "00_setup.R"))

stop_if_missing(c(here::here("data", "dt_states.rds")))
dt <- readRDS(here::here("data", "dt_states.rds")) |> data.table::as.data.table()

# Ensure factors
dt[, position := factor(position, levels = c("alpha","beta","gamma"))]
dt[, ola := factor(ola)]

# Controls (adjust if you have additional covariates)
# Convert to sensible types
dt[, woman := as.integer(to01(woman))]
# education/employment may be categorical — keep as factor if not numeric
if (!is.numeric(dt$education)) dt[, education := factor(education)]
if (!is.numeric(dt$employment)) dt[, employment := factor(employment)]

# ---- Random-intercept probit via glmer (lme4) ----
# NOTE: This is the R analog of xtprobit, re.
# We keep interpretation associative; report AMEs.

m_gt <- lme4::glmer(
  trust ~ position + edad + woman + education + employment + ola + (1|id),
  data = dt,
  family = binomial(link = "probit"),
  control = lme4::glmerControl(optimizer = "bobyqa")
)

m_nh <- lme4::glmer(
  trust_nh ~ position + edad + woman + education + employment + ola + (1|id),
  data = dt,
  family = binomial(link = "probit"),
  control = lme4::glmerControl(optimizer = "bobyqa")
)

# ---- AMEs for position (α reference) ----
ame_gt <- marginaleffects::avg_slopes(m_gt, variables = "position")
ame_nh <- marginaleffects::avg_slopes(m_nh, variables = "position")

ame_tbl <- dplyr::bind_rows(
  dplyr::mutate(as.data.frame(ame_gt), outcome = "generalized_trust"),
  dplyr::mutate(as.data.frame(ame_nh), outcome = "neighborhood_trust")
)

readr::write_csv(ame_tbl, here::here("output", "trust_ame_table.csv"))

# ---- Wald / contrast: (γ − β) on AME scale ----
# We compute the difference in average slopes for gamma vs beta.
# This is the key SSR contrast you flagged.

contrast_gt <- marginaleffects::avg_comparisons(
  m_gt,
  variables = list(position = c("gamma", "beta")),
  comparison = "difference"
)

contrast_nh <- marginaleffects::avg_comparisons(
  m_nh,
  variables = list(position = c("gamma", "beta")),
  comparison = "difference"
)

sink(here::here("output", "wald_gamma_minus_beta.txt"))
cat("Contrast (gamma - beta), generalized trust:\n")
print(contrast_gt)
cat("\nContrast (gamma - beta), neighborhood trust:\n")
print(contrast_nh)
sink()

# ---- Minimal model summary for archive ----
sink(here::here("output", "trust_models_glance.txt"))
cat("Generalized trust model:\n")
print(broom.mixed::glance(m_gt))
cat("\nNeighborhood trust model:\n")
print(broom.mixed::glance(m_nh))
sink()
