# ==============================================================================
# 03c_active_only_sensitivity.R — Sensitivity S7: Active-Only membership coding
# ------------------------------------------------------------------------------
# Runs key trust models using dt_states_cov_active_only.rds
# (LMM estimated with MEMBER_CODE_LOGIC = "active_only", c12 == 3 only)
#
# Compares AMEs against main model (any-member, c12 >= 2) stored in
# output/ame_all_models.csv (generated by 03_trust_models.R).
#
# OUTPUTS:
#   output/SI_S7_active_only_ames.csv     — AMEs under active-only coding
#   output/SI_S7_lmm_comparison.csv       — LMM fit comparison: any vs active
#   output/SI_S7_profiles_comparison.csv  — Profile comparison table
# ==============================================================================

options(marginaleffects_safe = FALSE)
source(here::here("code", "00_setup.R"))

suppressPackageStartupMessages({
  library(dplyr); library(tidyr); library(tibble); library(readr)
  library(lme4); library(marginaleffects); library(clubSandwich)
  library(sandwich); library(merDeriv)
})

NAGQ <- 9L   # faster for sensitivity; main paper uses 12

# ==============================================================================
# 1. LOAD DATA
# ==============================================================================
stop_if_missing(c(
  here::here("data", "dt_states_cov_active_only.rds"),
  here::here("data", "dt_analysis.rds")
))

dt_states_ao <- readRDS(here::here("data", "dt_states_cov_active_only.rds")) %>%
  as_tibble() %>%
  mutate(idencuesta = as.character(idencuesta))

dt_anal <- readRDS(here::here("data", "dt_analysis.rds")) %>%
  as_tibble() %>%
  rename(idencuesta = id) %>%
  mutate(idencuesta = as.character(idencuesta)) %>%
  select(idencuesta, ola, trust, trust_nh, edad, woman, education,
         employed, swb, couple, tinst)

cols_new <- setdiff(names(dt_anal), c("idencuesta", "ola",
                    setdiff(names(dt_states_ao), c("idencuesta", "ola"))))

dt <- left_join(
  dt_states_ao,
  dt_anal %>% select(all_of(c("idencuesta", "ola", cols_new))),
  by = c("idencuesta", "ola")
) %>%
  mutate(
    clase = case_when(
      position == "alpha" ~ 3L,
      position == "beta"  ~ 1L,
      position == "gamma" ~ 2L,
      TRUE                ~ NA_integer_
    ),
    clase_f = factor(clase, levels = c(2L, 1L, 3L)),  # γ = referencia
    ola_f   = factor(ola)
  )

message("N total: ", nrow(dt))
message("N con clase no-NA: ", sum(!is.na(dt$clase)))

# ==============================================================================
# 2. KEY TRUST MODELS (replicating Table 4 specs M1 and M2)
# ==============================================================================

CONTROLS_TRUST <- c("edad", "woman", "education", "swb", "employed", "couple", "tinst")
ctrl_use <- CONTROLS_TRUST[
  CONTROLS_TRUST %in% names(dt) &
  sapply(CONTROLS_TRUST, function(v) sum(!is.na(dt[[v]])) > 0)
]

run_spec <- function(outcome, controls, label) {
  fml_str <- if (length(controls) == 0) {
    paste0(outcome, " ~ clase_f + ola_f + (1 | idencuesta)")
  } else {
    paste0(outcome, " ~ clase_f + ", paste(controls, collapse = " + "),
           " + ola_f + (1 | idencuesta)")
  }
  fml <- as.formula(fml_str)
  d   <- dt %>% drop_na(all_of(c(outcome, "clase_f", controls))) %>%
               filter(!is.na(clase))

  message("  Fitting ", label, " | N=", nrow(d), " | fml: ", fml_str)

  tryCatch({
    m <- glmer(fml, data = d, family = binomial("probit"),
               nAGQ = NAGQ,
               control = glmerControl(optimizer = "bobyqa",
                                      optCtrl = list(maxfun = 2e5)))

    vcv <- tryCatch({
      v <- sandwich::vcovCL(m, cluster = ~idencuesta, type = "HC1")
      if (any(eigen(v, only.values = TRUE)$values < 0)) NULL else v
    }, error = function(e) NULL)

    ame <- avg_slopes(m, variables = "clase_f", type = "response",
                      vcov = if (!is.null(vcv)) vcv else TRUE)

    ame %>%
      as_tibble() %>%
      mutate(
        spec    = label,
        outcome = outcome,
        coding  = "active_only",
        N       = nrow(d)
      ) %>%
      select(spec, outcome, coding, N, contrast, estimate,
             std.error, statistic, p.value, conf.low, conf.high)
  }, error = function(e) {
    warning("Error in ", label, ": ", conditionMessage(e))
    tibble()
  })
}

message("\n--- Running active-only trust models ---")

ame_list <- list(
  run_spec("trust",    character(0),  "AO_M1_trust_noctrl"),
  run_spec("trust",    ctrl_use,      "AO_M2_trust_ctrl"),
  run_spec("trust_nh", character(0),  "AO_M3_trustnh_noctrl"),
  run_spec("trust_nh", ctrl_use,      "AO_M4_trustnh_ctrl")
)

ame_ao <- bind_rows(ame_list) %>%
  mutate(sig = case_when(
    p.value < .001 ~ "***",
    p.value < .01  ~ "**",
    p.value < .05  ~ "*",
    p.value < .10  ~ ".",
    TRUE           ~ ""
  ))

readr::write_csv(ame_ao, here::here("output", "SI_S7_active_only_ames.csv"))
cat("\n=== Active-only AMEs ===\n")
print(ame_ao %>% select(spec, outcome, contrast, estimate, std.error, p.value, sig), n = 40)

# ==============================================================================
# 3. LMM FIT COMPARISON TABLE
# ==============================================================================

fit_ao   <- readr::read_csv(here::here("output", "fit_table_cov_active_only.csv"),
                             show_col_types = FALSE)
# SI_lmm_fit.csv = fit_table_cov.csv (any_member); fallback to fit_table_cov.csv if missing
fit_main_path <- if (file.exists(here::here("output", "SI_lmm_fit.csv"))) {
  here::here("output", "SI_lmm_fit.csv")
} else {
  here::here("output", "fit_table_cov.csv")
}
fit_main <- readr::read_csv(fit_main_path, show_col_types = FALSE)

# If SI_lmm_fit.csv has a K_label column, clean it
if ("K_label" %in% names(fit_main)) {
  fit_main <- fit_main %>% mutate(K_label = as.character(K))
}

lmm_comp <- bind_rows(
  fit_main %>% select(K, BIC, AIC, logLik) %>% mutate(coding = "any_member"),
  fit_ao   %>% select(K, BIC, AIC, logLik) %>% mutate(coding = "active_only")
) %>%
  arrange(coding, K)

readr::write_csv(lmm_comp, here::here("output", "SI_S7_lmm_comparison.csv"))
cat("\n=== LMM Fit Comparison ===\n")
print(lmm_comp)

# ==============================================================================
# 4. PROFILE COMPARISON TABLE
# ==============================================================================

prof_ao   <- readr::read_csv(here::here("output", "latent_profiles_cov_K3_active_only.csv"),
                              show_col_types = FALSE)
prof_main <- readr::read_csv(here::here("output", "SI_profiles.csv"),
                              show_col_types = FALSE)

# Active-only: pivot to long with state mapping
domain_names <- c("nhg", "religious", "political", "union",
                  "professional", "charity", "sport", "student")

# Determine state mapping from profiles (same as main: State1=alpha, State2=gamma, State3=beta)
prof_ao_long <- prof_ao %>%
  mutate(domain = domain_names) %>%
  pivot_longer(starts_with("State_"), names_to = "raw_state", values_to = "prob_ao") %>%
  mutate(position = case_when(
    raw_state == "State_1" ~ "alpha",
    raw_state == "State_2" ~ "gamma",
    raw_state == "State_3" ~ "beta"
  ))

# Main profiles from SI_profiles.csv — check its structure
cat("\n--- SI_profiles.csv columns ---\n")
print(names(prof_main))
print(head(prof_main, 4))

readr::write_csv(prof_ao_long, here::here("output", "SI_S7_profiles_comparison.csv"))

# ==============================================================================
# 5. SUMMARY
# ==============================================================================

cat("\n", strrep("=", 65), "\n")
cat("[03c_active_only_sensitivity.R] DONE\n\n")
cat("OUTPUTS:\n")
cat("  SI_S7_active_only_ames.csv     — AMEs under active-only coding\n")
cat("  SI_S7_lmm_comparison.csv       — LMM BIC both codings\n")
cat("  SI_S7_profiles_comparison.csv  — Item-response probs active-only\n")
cat(strrep("=", 65), "\n")
