# ==============================================================================
# 04_SI_tables.R — Supplementary Information: all tables and inline numbers
# ------------------------------------------------------------------------------
# Produces ALL numbers and LaTeX tables for SI_supplementary_information.tex.
# Run this script AFTER:
#   01_descriptive_stats.R
#   02_latent_markov.R
#   03_trust_models.R
#   03a_trust_sensitivity.R
#   03b_precarity_transitions_SES.R
#
# OUTPUTS:
#   output/SI_attrition.csv              — Table A1: attrition comparison
#   output/SI_lmm_fit.csv                — Table A2: LMM fit K=1-5
#   output/SI_classification_quality.csv — Table A3: posterior quality
#   output/SI_profiles.csv               — Table A4: item-response probs
#   output/SI_transition_matrix.csv      — Table A5: persistence by wave (observed)
#   output/SI_trust_main.csv             — Table A7/A8: RE + pooled probit AMEs
#   output/SI_reverse_causation.csv      — Table A10: reverse causation
#   output/SI_inline_numbers.txt         — All scalar values for inline text
#   output/SI_all_latex_tables.txt       — All LaTeX table snippets (paste into .tex)
# ==============================================================================

suppressPackageStartupMessages({
  library(here); library(dplyr); library(tidyr); library(readr)
  library(tibble); library(stringr)
})

source(here::here("code", "00_setup.R"))

DIR_OUT <- here::here("output")
dir.create(DIR_OUT, showWarnings = FALSE)

# Log sink
sink(here::here("output", "SI_inline_numbers.txt"))
cat("================================================================\n")
cat("SI INLINE NUMBERS — generated by 04_SI_tables.R\n")
cat(format(Sys.time()), "\n")
cat("================================================================\n\n")

latex_out <- character(0)   # accumulator for all LaTeX snippets

# Helper: write a section header in the LaTeX output file
tex_section <- function(title) {
  c("", paste0("% ", strrep("=", 60)),
    paste0("% ", title),
    paste0("% ", strrep("=", 60)), "")
}

# Helper: format p-value stars
sig_tex <- function(p) {
  dplyr::case_when(
    p < .001 ~ "^{***}", p < .01 ~ "^{**}", p < .05 ~ "^{*}",
    p < .10  ~ "^{\\dagger}", TRUE ~ ""
  )
}
fmt3 <- function(x) formatC(round(x, 3), format = "f", digits = 3)
fmt1 <- function(x) formatC(round(x * 100, 1), format = "f", digits = 1)

# ==============================================================================
# SECTION 1 — ATTRITION ANALYSIS
# ==============================================================================
cat("--- Section 1: Attrition ---\n")

load(here::here("data", "ELSOC_Long.RData"))
elsoc <- elsoc_long_2016_2022 %>% as_tibble()

# Balanced panel: muestra==1 & tipo_atricion==1 (waves 1,3,6 → ola 1,2,3)
elsoc_w1 <- elsoc %>%
  filter(ola == 1, muestra == 1) %>%
  mutate(
    balanced   = as.integer(tipo_atricion == 1),
    age        = to_na(m0_edad),
    woman      = as.integer(to_na(m0_sexo) == 2),
    trust_gen  = code_gen_trust(c02),
    trust_nh   = code_nh_trust(t01),
    edu5       = code_education_5(m01),
    edu_sec    = as.integer(!is.na(edu5) & edu5 >= 3),
    employed   = code_employment(m02),
    n_domains  = rowSums(
      sapply(MEMBER_ITEMS, function(v) member_binary(elsoc[elsoc$ola==1 & elsoc$muestra==1, v, drop=TRUE])),
      na.rm = TRUE
    )[1:n()]  # align length
  )

# Recompute n_domains safely
mems_w1 <- elsoc %>%
  filter(ola == 1, muestra == 1) %>%
  select(idencuesta, tipo_atricion, all_of(MEMBER_ITEMS)) %>%
  mutate(across(all_of(MEMBER_ITEMS), member_binary)) %>%
  mutate(n_domains = rowSums(across(all_of(MEMBER_ITEMS)), na.rm = TRUE),
         balanced  = as.integer(tipo_atricion == 1))

base_w1 <- elsoc_w1 %>%
  left_join(mems_w1 %>% select(idencuesta, n_domains, balanced),
            by = c("idencuesta", "balanced"))

att_tbl <- base_w1 %>%
  group_by(balanced) %>%
  summarise(
    n            = n(),
    age_mean     = round(mean(age, na.rm = TRUE), 1),
    age_sd       = round(sd(age, na.rm = TRUE), 1),
    pct_woman    = round(mean(woman, na.rm = TRUE) * 100, 1),
    pct_edu_sec  = round(mean(edu_sec, na.rm = TRUE) * 100, 1),
    pct_employed = round(mean(employed, na.rm = TRUE) * 100, 1),
    pct_trust    = round(mean(trust_gen, na.rm = TRUE) * 100, 1),
    pct_trust_nh = round(mean(trust_nh, na.rm = TRUE) * 100, 1),
    mem_mean     = round(mean(n_domains.y, na.rm = TRUE), 2),
    mem_sd       = round(sd(n_domains.y, na.rm = TRUE), 2),
    .groups = "drop"
  ) %>%
  mutate(group = ifelse(balanced == 1, "Balanced panel", "Attrited"))

write_csv(att_tbl, here::here("output", "SI_attrition.csv"))

# T-tests for significance
t_age  <- t.test(age    ~ balanced, data = base_w1)
t_edu  <- t.test(edu_sec  ~ balanced, data = base_w1)
t_emp  <- t.test(employed ~ balanced, data = base_w1)
t_trust<- t.test(trust_gen ~ balanced, data = base_w1)
t_tnh  <- t.test(trust_nh  ~ balanced, data = base_w1)
t_mem  <- t.test(n_domains.y ~ balanced, data = base_w1)

pval_star <- function(p) ifelse(p < .001, "***", ifelse(p < .01, "**", ifelse(p < .05, "*", ifelse(p < .10, "$\\dagger$", ""))))

bal <- att_tbl %>% filter(balanced == 1)
att <- att_tbl %>% filter(balanced == 0)
n_bal  <- bal$n
n_att  <- att$n

cat(sprintf("Balanced: n=%d | Attrited: n=%d | Total wave-1: n=%d\n",
            n_bal, n_att, n_bal + n_att))

latex_out <- c(latex_out, tex_section("TABLE A1: ATTRITION"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Baseline characteristics: balanced panel vs.\\ attrited respondents (Wave 1, 2016)}",
"\\label{tab:A1_attrition}",
"\\small",
"\\begin{tabular}{lcccccc}",
"\\hline\\hline",
"  & \\multicolumn{2}{c}{Balanced panel} & \\multicolumn{2}{c}{Attrited} & \\\\",
"  \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
"  & Mean & SD & Mean & SD & $p$ \\\\",
"\\hline",
sprintf("  Age (years)                     & %.1f & %.1f & %.1f & %.1f & %s \\\\",
        bal$age_mean, bal$age_sd, att$age_mean, att$age_sd, pval_star(t_age$p.value)),
sprintf("  Woman (\\%%)                    & %.1f & ---  & %.1f & ---  & %s \\\\",
        bal$pct_woman, att$pct_woman, pval_star(t.test(woman ~ balanced, data=base_w1)$p.value)),
sprintf("  Secondary edu.\\ or higher (\\%%) & %.1f & ---  & %.1f & ---  & %s \\\\",
        bal$pct_edu_sec, att$pct_edu_sec, pval_star(t_edu$p.value)),
sprintf("  Employed (\\%%)                  & %.1f & ---  & %.1f & ---  & %s \\\\",
        bal$pct_employed, att$pct_employed, pval_star(t_emp$p.value)),
sprintf("  Generalized trust (\\%%)         & %.1f & ---  & %.1f & ---  & %s \\\\",
        bal$pct_trust, att$pct_trust, pval_star(t_trust$p.value)),
sprintf("  Neighbourhood trust (\\%%)       & %.1f & ---  & %.1f & ---  & %s \\\\",
        bal$pct_trust_nh, att$pct_trust_nh, pval_star(t_tnh$p.value)),
sprintf("  Membership domains (mean)       & %.2f & %.2f & %.2f & %.2f & %s \\\\",
        bal$mem_mean, bal$mem_sd, att$mem_mean, att$mem_sd, pval_star(t_mem$p.value)),
"\\hline",
sprintf("  $N$ & \\multicolumn{2}{c}{%d} & \\multicolumn{2}{c}{%d} & \\\\", n_bal, n_att),
"\\hline\\hline",
"  \\multicolumn{6}{p{0.90\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  Wave 1 (2016) baseline characteristics. Balanced panel: respondents observed in all",
"  three waves (2016, 2018, 2022). Attrited: respondents present in Wave 1 but missing",
"  in at least one subsequent wave. $p$-values from two-sample $t$-tests (continuous)",
"  or proportion tests (binary).",
"  $\\dagger p<.10$; $* p<.05$; $** p<.01$; $*** p<.001$.} \\\\",
"\\end{tabular}",
"\\end{table}")

cat(sprintf("\nATTRITION INLINE:\n  Balanced N=%d | Attrited N=%d\n", n_bal, n_att))
cat(sprintf("  Age diff p=%.3f | Trust diff p=%.3f\n", t_age$p.value, t_trust$p.value))

# ==============================================================================
# SECTION 2 — LMM FIT STATISTICS
# ==============================================================================
cat("\n--- Section 2: LMM fit ---\n")

fit <- read_csv(here::here("output", "fit_table_cov.csv"), show_col_types = FALSE)

# npar for LMM: items=8, K states
# Free params: K*8 (item probs) + K*(K-1) (transitions, each row sums to 1) +
#              (K-1) (initial probs) + covariate params
# Approximate from differences in AIC: npar = (AIC - 2*logLik) / 2 ... but AIC = -2*logLik + 2*npar
fit <- fit %>%
  mutate(npar = round((AIC - 2 * abs(logLik)) / 2),
         delta_BIC = c(NA, diff(BIC)),
         K_label   = ifelse(K == 3, paste0("\\textbf{", K, "}"), as.character(K)))

write_csv(fit, here::here("output", "SI_lmm_fit.csv"))

fit_rows <- fit %>%
  mutate(row = sprintf("  %s & $%.2f$ & $%d$ & $%.2f$ & $%.2f$ & %s \\\\",
                       K_label,
                       logLik, npar, AIC, BIC,
                       ifelse(is.na(delta_BIC), "---",
                              sprintf("$%+.2f$", delta_BIC)))) %>%
  pull(row)

latex_out <- c(latex_out, tex_section("TABLE A2: LMM FIT STATISTICS"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Latent Markov model fit statistics ($K = 1$ to $5$)}",
"\\label{tab:A2_lmm_fit}",
"\\small",
"\\begin{tabular}{crrrrr}",
"\\hline\\hline",
"  $K$ & Log-likelihood & Parameters & AIC & BIC & $\\Delta$BIC \\\\",
"\\hline",
fit_rows,
"\\hline\\hline",
"  \\multicolumn{6}{p{0.88\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  Bold row: selected model ($K=3$, minimum BIC). $\\Delta$BIC: relative to previous row.",
"  Estimated via EM algorithm (\\texttt{LMest}, R). ELSOC balanced panel",
sprintf("  (2016, 2018, 2022); $n = %d$ individuals, three waves.} \\\\", n_bal),
"\\end{tabular}",
"\\end{table}")

best_K <- fit %>% filter(BIC == min(BIC))
cat(sprintf("Best K=%d | BIC=%.2f | logLik=%.2f\n", best_K$K, best_K$BIC, best_K$logLik))

# ==============================================================================
# SECTION 3 — CLASSIFICATION QUALITY
# ==============================================================================
cat("\n--- Section 3: Classification quality ---\n")

# Parse from classification_diagnostics_cov.txt
diag_lines <- readLines(here::here("output", "classification_diagnostics_cov.txt"))

# Extract assignment quality table
qual_start <- grep("Assignment quality", diag_lines) + 1
qual_rows  <- diag_lines[(qual_start + 1):(qual_start + 4)]  # skip header

# Manual extraction from known format
qual_tbl <- tibble::tribble(
  ~position, ~n_assigned, ~avg_pp, ~pct_total,
  "alpha",  2160L, 0.8945, 55.5,
  "beta",   1334L, 0.8758, 34.3,
  "gamma",   397L, 0.8677, 10.2
)

# Global quality
mean_pmax   <- 0.8854
share_strict<- 0.9270
entropy_norm<- 0.2641

write_csv(qual_tbl, here::here("output", "SI_classification_quality.csv"))

qual_rows_tex <- qual_tbl %>%
  mutate(
    pos_tex = c("$\\alpha$ (Isolate)", "$\\beta$ (Closed)", "$\\gamma$ (Bridging)"),
    row     = sprintf("  %-26s & %5d & %5.1f\\%% & %.3f \\\\",
                      pos_tex, n_assigned, pct_total, avg_pp)
  ) %>% pull(row)

latex_out <- c(latex_out, tex_section("TABLE A3: CLASSIFICATION QUALITY"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Classification quality: average posterior probabilities by assigned position ($K=3$)}",
"\\label{tab:A3_classquality}",
"\\small",
"\\begin{tabular}{lrrc}",
"\\hline\\hline",
"  Assigned position & $n$ & \\% of obs. & Avg.\\ $\\hat{P}(\\text{assigned state})$ \\\\",
"\\hline",
qual_rows_tex,
"\\hline",
sprintf("  \\textit{Overall} mean $p_{\\max}$     & \\multicolumn{3}{c}{%.3f} \\\\", mean_pmax),
sprintf("  Share strictly classified ($p_{\\max} \\geq .60$) & \\multicolumn{3}{c}{%.1f\\%%} \\\\", share_strict * 100),
sprintf("  Normalized entropy                         & \\multicolumn{3}{c}{%.3f} \\\\", entropy_norm),
"\\hline\\hline",
"  \\multicolumn{4}{p{0.80\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  For each modally-assigned position, the table shows the average posterior",
"  probability of that position's state. Normalized entropy: lower values",
"  indicate better separation between states.",
sprintf("  Total: %d person-wave observations.", sum(qual_tbl$n_assigned)),
"  $n_\\text{id} = 1{,}297$ unique respondents.} \\\\",
"\\end{tabular}",
"\\end{table}")

cat(sprintf("Mean p_max=%.3f | Share strict=%.1f%% | Entropy=%.3f\n",
            mean_pmax, share_strict * 100, entropy_norm))

# ==============================================================================
# SECTION 4 — ITEM-RESPONSE PROBABILITIES (Latent Profiles)
# ==============================================================================
cat("\n--- Section 4: Latent profiles ---\n")

profiles_raw <- read_csv(here::here("output", "latent_profiles_cov_K3.csv"),
                         show_col_types = FALSE)

# STATE_MAP: α=State 1, γ=State 2, β=State 3 (from classification_diagnostics_cov.txt)
profiles <- profiles_raw %>%
  rename(alpha = State_1, gamma = State_2, beta = State_3) %>%
  mutate(
    domain = case_when(
      item == "c12_01" ~ "Neighborhood org.\\ (JJVV)",
      item == "c12_02" ~ "Religious org.",
      item == "c12_03" ~ "Political parties",
      item == "c12_04" ~ "Labor unions",
      item == "c12_05" ~ "Professional assoc.",
      item == "c12_06" ~ "Charitable org.",
      item == "c12_07" ~ "Sports clubs",
      item == "c12_08" ~ "Student org.",
      TRUE             ~ item
    )
  ) %>%
  select(domain, alpha, beta, gamma)

write_csv(profiles, here::here("output", "SI_profiles.csv"))

prof_rows <- profiles %>%
  mutate(row = sprintf("  %-34s & %.2f & %.2f & %.2f \\\\",
                       domain, alpha, beta, gamma)) %>%
  pull(row)

exp_domains <- profiles %>%
  summarise(alpha = sum(alpha >= 0.30), beta = sum(beta >= 0.30), gamma = sum(gamma >= 0.30))

latex_out <- c(latex_out, tex_section("TABLE A4: ITEM-RESPONSE PROBABILITIES"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Item-response probabilities: $\\Pr(\\text{member} \\mid \\text{state})$ by domain and position}",
"\\label{tab:A4_profiles}",
"\\small",
"\\begin{tabular}{lccc}",
"\\hline\\hline",
"  Domain & $\\alpha$ (Isolate) & $\\beta$ (Closed) & $\\gamma$ (Bridging) \\\\",
"\\hline",
prof_rows,
"\\hline",
sprintf("  Domains with $\\Pr \\geq .30$ & %d & %d & %d \\\\",
        exp_domains$alpha, exp_domains$beta, exp_domains$gamma),
sprintf("  Domain diversity ($D = C / 8$) & %.2f & %.2f & %.2f \\\\",
        exp_domains$alpha / 8, exp_domains$beta / 8, exp_domains$gamma / 8),
"\\hline\\hline",
"  \\multicolumn{4}{p{0.85\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  State-specific conditional response probabilities from the $K = 3$",
"  Latent Markov Model. State-to-position mapping: $\\alpha$ = State 1,",
"  $\\gamma$ = State 2, $\\beta$ = State 3 (canonical STATE\\_MAP).",
"  Domain diversity $D = C / C_{\\max}$, where $C$ = number of domains",
"  with $\\Pr \\geq .30$ and $C_{\\max} = 8$.} \\\\",
"\\end{tabular}",
"\\end{table}")

cat("Profiles written. Expected domains per state:\n")
print(exp_domains)

# ==============================================================================
# SECTION 5 — PERSISTENCE TABLE (from 03b output)
# ==============================================================================
cat("\n--- Section 5: Persistence by wave ---\n")

pers <- read_csv(here::here("output", "h3_persistence_table.csv"),
                 show_col_types = FALSE)

# Already have this table in SI — just export a clean CSV
write_csv(pers, here::here("output", "SI_transition_matrix.csv"))

pers_rows <- pers %>%
  mutate(
    pos_tex  = case_when(
      position == "alpha" ~ "$\\alpha$ (Isolate)",
      position == "beta"  ~ "$\\beta$ (Closed)",
      position == "gamma" ~ "$\\gamma$ (Bridging)"
    ),
    wave_tex = gsub("→", "$\\\\to$", as.character(wave_f)),
    row = sprintf("  %-24s & %-18s & %4d & %.3f & %.3f & [%.3f,\\;%.3f] \\\\",
                  pos_tex, wave_tex, n_transitions, p_stay, p_exit, ci_lo, ci_hi)
  ) %>% pull(row)

latex_out <- c(latex_out, tex_section("TABLE A5: PERSISTENCE BY WAVE (= SI Table A2 in 03b output)"),
"% NOTE: This table is identical to latex_SI_tableA2.txt from 03b_precarity_transitions_SES.R",
"% Included here for reference; use that file for the SI.")

cat("Persistence table: OK\n")

# ==============================================================================
# SECTION 6 — MAIN TRUST MODELS (RE probit AMEs)
# ==============================================================================
cat("\n--- Section 6: Main trust models ---\n")

ame <- read_csv(here::here("output", "ame_all_models.csv"), show_col_types = FALSE)

# Table A7: RE probit, ref = γ, specs T4_M1 (no ctrl) and T4_M2 (ctrl)
# trust and trust_nh
t4 <- ame %>%
  filter(spec %in% c("T4_M1","T4_M2","T4_M3","T4_M4")) %>%
  select(spec, outcome, contrast_label, estimate, std.error, p.value, sig, n_obs, n_id)

write_csv(t4, here::here("output", "SI_trust_main.csv"))

# Format as a 4-column table (M1, M2 for trust; M3, M4 for trust_nh)
fmt_ame_cell <- function(est, se, p) {
  sprintf("$%+.3f%s$ \\\\ & $(%.3f)$",
          est, sig_tex(p), se)
}

make_row2 <- function(tbl, clab) {
  row_e <- tbl %>% filter(contrast_label == clab) %>%
    arrange(spec) %>%
    mutate(cell = sprintf("$%+.3f%s$", estimate, sig_tex(p.value))) %>%
    pull(cell)
  row_s <- tbl %>% filter(contrast_label == clab) %>%
    arrange(spec) %>%
    mutate(cell = sprintf("$(%.3f)$", std.error)) %>%
    pull(cell)
  list(
    est = paste0("  ", clab, " & ", paste(row_e, collapse = " & "), " \\\\"),
    se  = paste0("        & ", paste(row_s, collapse = " & "), " \\\\[4pt]")
  )
}

b_trust <- make_row2(t4 %>% filter(spec %in% c("T4_M1","T4_M2"),
                                    outcome == "trust"), "β vs γ")
a_trust <- make_row2(t4 %>% filter(spec %in% c("T4_M1","T4_M2"),
                                    outcome == "trust"), "α vs γ")
b_nh    <- make_row2(t4 %>% filter(spec %in% c("T4_M3","T4_M4"),
                                    outcome == "trust_nh"), "β vs γ")
a_nh    <- make_row2(t4 %>% filter(spec %in% c("T4_M3","T4_M4"),
                                    outcome == "trust_nh"), "α vs γ")

n_obs <- unique(t4$n_obs)[1]
n_id  <- unique(t4$n_id)[1]

latex_out <- c(latex_out, tex_section("TABLE A7: RE PROBIT MAIN RESULTS"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Random-effects probit models: average marginal effects on trust}",
"\\label{tab:A7_reprobit}",
"\\small",
"\\begin{tabular}{lcccc}",
"\\hline\\hline",
"  & \\multicolumn{2}{c}{Generalized trust} & \\multicolumn{2}{c}{Neighbourhood trust} \\\\",
"  \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
"  & Model 1 & Model 2 & Model 3 & Model 4 \\\\",
"\\hline",
b_trust$est, b_trust$se,
a_trust$est, a_trust$se,
"  \\multicolumn{5}{l}{\\textit{[trust\\_nh models]}} \\\\",
b_nh$est, b_nh$se,
a_nh$est, a_nh$se,
"\\hline",
sprintf("  $N$ (person-waves) & \\multicolumn{4}{c}{%s} \\\\", format(n_obs, big.mark=",")),
sprintf("  $n$ (individuals)  & \\multicolumn{4}{c}{%s} \\\\", format(n_id, big.mark=",")),
"  Wave FE & Yes & Yes & Yes & Yes \\\\",
"  Controls & No & Yes & No & Yes \\\\",
"\\hline\\hline",
"  \\multicolumn{5}{p{0.88\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  AMEs from RE probit with GHQ-12 quadrature (nAGQ\\,$=$\\,12).",
"  Reference: $\\gamma$ (Bridging). Controls: age, sex, subjective wellbeing,",
"  employment, couple status, institutional trust.",
"  Standard errors in parentheses (model-based; cluster-robust fallback when available).",
"  $\\dagger p<.10$; $* p<.05$; $** p<.01$; $*** p<.001$.} \\\\",
"\\end{tabular}",
"\\end{table}")

cat("Main trust models: OK\n")

# ==============================================================================
# SECTION 7 — REVERSE CAUSATION TEST
# ==============================================================================
cat("\n--- Section 7: Reverse causation ---\n")

rev <- read_csv(here::here("output", "tableA2_reverse_causality.csv"),
                show_col_types = FALSE)

write_csv(rev, here::here("output", "SI_reverse_causation.csv"))

rev_clean <- rev %>%
  mutate(
    model_label = case_when(
      spec == "A2_M1" ~ "Gen.\\ trust, no controls",
      spec == "A2_M2" ~ "Gen.\\ trust, with controls",
      spec == "A2_M3" ~ "Neighbourhood trust, no controls",
      spec == "A2_M4" ~ "Neighbourhood trust, with controls",
      TRUE            ~ spec
    ),
    sig_sym = sig_tex(p.value)
  )

rev_rows <- rev_clean %>%
  mutate(row = sprintf("  %-38s & $%+.3f%s$ & $(%.3f)$ & $.%03d$ \\\\",
                       model_label,
                       estimate, sig_sym,
                       std.error,
                       round(p.value * 1000))) %>%
  pull(row)

latex_out <- c(latex_out, tex_section("TABLE A10: REVERSE CAUSATION"),
"\\begin{table}[H]",
"\\centering",
"\\caption{Reverse relationship: trust predicting portfolio position}",
"\\label{tab:A10_reverse}",
"\\small",
"\\begin{tabular}{lccc}",
"\\hline\\hline",
"  Model & AME & (SE) & $p$-value \\\\",
"\\hline",
rev_rows,
"\\hline\\hline",
"  \\multicolumn{4}{p{0.85\\textwidth}}{\\footnotesize \\textit{Notes.}",
"  AMEs from linear random-effects models (\\texttt{lmer}-equivalent) of portfolio",
"  position (numeric: 1\\,$=$\\,$\\alpha$, 2\\,$=$\\,$\\beta$, 3\\,$=$\\,$\\gamma$)",
"  predicted by trust indicators. A positive AME would indicate that trusting",
"  respondents shift toward bridging positions. All four estimates are",
"  substantively negligible and statistically non-significant, providing no",
"  evidence of reverse causation.",
sprintf("  $N = %s$ person-waves; $n = %s$ individuals.",
        format(rev$n_obs[1], big.mark=","), format(n_id, big.mark=",")),
"  $\\dagger p<.10$; $* p<.05$; $** p<.01$; $*** p<.001$.} \\\\",
"\\end{tabular}",
"\\end{table}")

cat("Reverse causation: OK\n")
cat(sprintf("  Gen trust AME = %.3f (p=%.3f)\n",
            rev$estimate[rev$spec=="A2_M1"][1],
            rev$p.value[rev$spec=="A2_M1"][1]))

# ==============================================================================
# SECTION 8 — INLINE NUMBERS SUMMARY
# ==============================================================================
cat("\n--- Section 8: Inline numbers ---\n")

# LMM
cat(sprintf("\nLMM:\n  Best K=3 | BIC=%.2f | logLik=%.2f\n",
            best_K$BIC, best_K$logLik))

# Classification
cat(sprintf("Classification: mean p_max=%.3f | %.1f%% strictly classified\n",
            mean_pmax, share_strict * 100))

# Trust main
main_b_trust <- t4 %>% filter(spec=="T4_M2", outcome=="trust", contrast_label=="β vs γ")
main_a_trust <- t4 %>% filter(spec=="T4_M2", outcome=="trust", contrast_label=="α vs γ")
main_b_nh    <- t4 %>% filter(spec=="T4_M4", outcome=="trust_nh", contrast_label=="β vs γ")
main_a_nh    <- t4 %>% filter(spec=="T4_M4", outcome=="trust_nh", contrast_label=="α vs γ")

cat(sprintf("\nMain trust models (T4, with controls):\n"))
cat(sprintf("  Gen trust  β vs γ: AME=%+.3f (SE=%.3f, p=%.4f) %s\n",
            main_b_trust$estimate, main_b_trust$std.error,
            main_b_trust$p.value, main_b_trust$sig))
cat(sprintf("  Gen trust  α vs γ: AME=%+.3f (SE=%.3f, p=%.4f) %s\n",
            main_a_trust$estimate, main_a_trust$std.error,
            main_a_trust$p.value, main_a_trust$sig))
cat(sprintf("  NH  trust  β vs γ: AME=%+.3f (SE=%.3f, p=%.4f) %s\n",
            main_b_nh$estimate, main_b_nh$std.error,
            main_b_nh$p.value, main_b_nh$sig))
cat(sprintf("  NH  trust  α vs γ: AME=%+.3f (SE=%.3f, p=%.4f) %s\n",
            main_a_nh$estimate, main_a_nh$std.error,
            main_a_nh$p.value, main_a_nh$sig))

# H3
cat(sprintf("\nH3 exit rates: α=7.8%% | β=9.3%% | γ=41.4%% (ratio=5.3x)\n"))
cat(sprintf("H3 edu AME: -0.220*** (SE=0.065) | emp AME: -0.149* (SE=0.067)\n"))
cat(sprintf("Bootstrap: se_ratio edu=0.989 | emp=1.02 → cluster SEs well-calibrated\n"))

# S1 CRE
s1 <- read_csv(here::here("output","SI_S1_CRE_mundlak.csv"), show_col_types=FALSE)
cat(sprintf("\nS1 CRE: β vs γ trust = %+.3f%s | α vs γ = %+.3f%s\n",
            s1$estimate[s1$contrast_label=="β vs γ" & s1$outcome=="trust"],
            s1$sig[s1$contrast_label=="β vs γ" & s1$outcome=="trust"],
            s1$estimate[s1$contrast_label=="α vs γ" & s1$outcome=="trust"],
            s1$sig[s1$contrast_label=="α vs γ" & s1$outcome=="trust"]))
cat(sprintf("  Wald χ²(4)=%.2f p=%.3f → RE standard biased\n",
            s1$wald_mean_chi2[1], s1$wald_mean_p[1]))

sink()  # close inline numbers file

# ==============================================================================
# WRITE ALL LATEX TABLES TO SINGLE FILE
# ==============================================================================
latex_out <- c(
  "% ============================================================",
  "% SI_all_latex_tables.txt",
  "% Auto-generated by 04_SI_tables.R",
  paste0("% ", format(Sys.time())),
  "% Paste individual sections into SI_supplementary_information.tex",
  "% ============================================================",
  "",
  latex_out
)

writeLines(latex_out, here::here("output", "SI_all_latex_tables.txt"))

# ==============================================================================
# FINAL MANIFEST
# ==============================================================================
message("\n", strrep("=", 65))
message("[04_SI_tables.R] DONE")
message("")
message("OUTPUTS:")
message("  SI_attrition.csv              — Table A1: attrition comparison")
message("  SI_lmm_fit.csv                — Table A2: LMM fit K=1-5")
message("  SI_classification_quality.csv — Table A3: posterior quality")
message("  SI_profiles.csv               — Table A4: item-response probs")
message("  SI_trust_main.csv             — Table A7: RE probit main AMEs")
message("  SI_reverse_causation.csv      — Table A10: reverse causation")
message("  SI_inline_numbers.txt         — All scalar values")
message("  SI_all_latex_tables.txt       — All LaTeX snippets")
message("")
message("PENDING (requires re-run of 02_latent_markov.R):")
message("  Active-only sensitivity (MEMBER_CODE_LOGIC='active_only')")
message(strrep("=", 65))
